name: Generate Data for Snake
on:
  push:
    branches:
      - '*'  # Trigger on any branch or give 'main' for triggering with any changes done to main branch
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
    
      #Generate Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: VarunTej06
          svg_out_path: dist/github-contribution-grid-snake.svg
      
      # Deploy to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
